name: 🚀 Deploy portfolio on FTP

on: push

# Let's test this first before creating a release.
# on: 
  # release:
    # types: [created]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        log-level: verbose
        server: ftp://skopp.sk
        server-dir: /sub/jules/
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASS }}
        dry-run: true
