name: 🚀 Deploy portfolio on FTP

on: 
  release:
    types: [created]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        protocol: ftps
        server: skopp.sk
        server-dir: sub/jules/
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASS }}
